//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.32559.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0", IsNullable=false)]
public partial class statementProduction {
    
    private statementProductionPrologue prologueField;
    
    private statementProductionEnvelope[] envelopeField;
    
    private statementProductionEpilogue epilogueField;
    
    private string typeField;
    
    private System.DateTime revisionField;
    
    /// <remarks/>
    public statementProductionPrologue prologue {
        get {
            return this.prologueField;
        }
        set {
            this.prologueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("envelope")]
    public statementProductionEnvelope[] envelope {
        get {
            return this.envelopeField;
        }
        set {
            this.envelopeField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEpilogue epilogue {
        get {
            return this.epilogueField;
        }
        set {
            this.epilogueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionPrologue {
    
    private ushort institutionIdField;
    
    private string institutionNameField;
    
    private string databaseNameField;
    
    private System.DateTime productionDateField;
    
    private string productionTimeField;
    
    private System.DateTime statementEndingDateField;
    
    private string typeField;
    
    /// <remarks/>
    public ushort institutionId {
        get {
            return this.institutionIdField;
        }
        set {
            this.institutionIdField = value;
        }
    }
    
    /// <remarks/>
    public string institutionName {
        get {
            return this.institutionNameField;
        }
        set {
            this.institutionNameField = value;
        }
    }
    
    /// <remarks/>
    public string databaseName {
        get {
            return this.databaseNameField;
        }
        set {
            this.databaseNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime productionDate {
        get {
            return this.productionDateField;
        }
        set {
            this.productionDateField = value;
        }
    }
    
    /// <remarks/>
    public string productionTime {
        get {
            return this.productionTimeField;
        }
        set {
            this.productionTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime statementEndingDate {
        get {
            return this.statementEndingDateField;
        }
        set {
            this.statementEndingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelope {
    
    private statementProductionEnvelopePerson personField;
    
    private statementProductionEnvelopeAddress addressField;
    
    private statementProductionEnvelopeStatement statementField;
    
    private string typeField;
    
    /// <remarks/>
    public statementProductionEnvelopePerson person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeAddress address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatement statement {
        get {
            return this.statementField;
        }
        set {
            this.statementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopePerson {
    
    private uint serialField;
    
    private string firstNameField;
    
    private string middleNameField;
    
    private string lastNameField;
    
    private string suffixField;
    
    private string typeField;
    
    /// <remarks/>
    public uint serial {
        get {
            return this.serialField;
        }
        set {
            this.serialField = value;
        }
    }
    
    /// <remarks/>
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string middleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string suffix {
        get {
            return this.suffixField;
        }
        set {
            this.suffixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeAddress {
    
    private uint addressSerialField;
    
    private statementProductionEnvelopeAddressCategory categoryField;
    
    private string streetField;
    
    private string cityField;
    
    private string stateField;
    
    private ushort postalCodeField;
    
    private bool postalCodeFieldSpecified;
    
    private string typeField;
    
    /// <remarks/>
    public uint addressSerial {
        get {
            return this.addressSerialField;
        }
        set {
            this.addressSerialField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeAddressCategory category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public string street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public ushort postalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool postalCodeSpecified {
        get {
            return this.postalCodeFieldSpecified;
        }
        set {
            this.postalCodeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeAddressCategory {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatement {
    
    private System.DateTime beginningStatementDateField;
    
    private System.DateTime endingStatementDateField;
    
    private statementProductionEnvelopeStatementAccount accountField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime beginningStatementDate {
        get {
            return this.beginningStatementDateField;
        }
        set {
            this.beginningStatementDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime endingStatementDate {
        get {
            return this.endingStatementDateField;
        }
        set {
            this.endingStatementDateField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccount account {
        get {
            return this.accountField;
        }
        set {
            this.accountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccount {
    
    private uint serialField;
    
    private uint accountNumberField;
    
    private byte typeSerialField;
    
    private string typeDescriptionField;
    
    private byte relationshipSerialField;
    
    private string relationshipDescriptionField;
    
    private statementProductionEnvelopeStatementAccountEStatementOption eStatementOptionField;
    
    private statementProductionEnvelopeStatementAccountEStatementNotification eStatementNotificationField;
    
    private string eStatementEmailAddressField;
    
    private System.DateTime openDateField;
    
    private statementProductionEnvelopeStatementAccountPerson personField;
    
    private statementProductionEnvelopeStatementAccountSubAccount[] subAccountField;
    
    private string typeField;
    
    /// <remarks/>
    public uint serial {
        get {
            return this.serialField;
        }
        set {
            this.serialField = value;
        }
    }
    
    /// <remarks/>
    public uint accountNumber {
        get {
            return this.accountNumberField;
        }
        set {
            this.accountNumberField = value;
        }
    }
    
    /// <remarks/>
    public byte typeSerial {
        get {
            return this.typeSerialField;
        }
        set {
            this.typeSerialField = value;
        }
    }
    
    /// <remarks/>
    public string typeDescription {
        get {
            return this.typeDescriptionField;
        }
        set {
            this.typeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public byte relationshipSerial {
        get {
            return this.relationshipSerialField;
        }
        set {
            this.relationshipSerialField = value;
        }
    }
    
    /// <remarks/>
    public string relationshipDescription {
        get {
            return this.relationshipDescriptionField;
        }
        set {
            this.relationshipDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountEStatementOption eStatementOption {
        get {
            return this.eStatementOptionField;
        }
        set {
            this.eStatementOptionField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountEStatementNotification eStatementNotification {
        get {
            return this.eStatementNotificationField;
        }
        set {
            this.eStatementNotificationField = value;
        }
    }
    
    /// <remarks/>
    public string eStatementEmailAddress {
        get {
            return this.eStatementEmailAddressField;
        }
        set {
            this.eStatementEmailAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime openDate {
        get {
            return this.openDateField;
        }
        set {
            this.openDateField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountPerson person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("subAccount")]
    public statementProductionEnvelopeStatementAccountSubAccount[] subAccount {
        get {
            return this.subAccountField;
        }
        set {
            this.subAccountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountEStatementOption {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountEStatementNotification {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountPerson {
    
    private uint serialField;
    
    private statementProductionEnvelopeStatementAccountPersonPersonLinkCategory personLinkCategoryField;
    
    private string firstNameField;
    
    private string middleNameField;
    
    private string lastNameField;
    
    private string suffixField;
    
    private string typeField;
    
    /// <remarks/>
    public uint serial {
        get {
            return this.serialField;
        }
        set {
            this.serialField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountPersonPersonLinkCategory personLinkCategory {
        get {
            return this.personLinkCategoryField;
        }
        set {
            this.personLinkCategoryField = value;
        }
    }
    
    /// <remarks/>
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string middleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    public string suffix {
        get {
            return this.suffixField;
        }
        set {
            this.suffixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountPersonPersonLinkCategory {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccount {
    
    private statementProductionEnvelopeStatementAccountSubAccountLoan loanField;
    
    private statementProductionEnvelopeStatementAccountSubAccountShare shareField;
    
    private string typeField;
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountLoan loan {
        get {
            return this.loanField;
        }
        set {
            this.loanField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountShare share {
        get {
            return this.shareField;
        }
        set {
            this.shareField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoan {
    
    private uint serialField;
    
    private byte idField;
    
    private string descriptionField;
    
    private statementProductionEnvelopeStatementAccountSubAccountLoanCategory categoryField;
    
    private byte typeSerialField;
    
    private string typeDescriptionField;
    
    private byte branchSerialField;
    
    private string branchDescriptionField;
    
    private ushort statementMailGroupSerialField;
    
    private string statementMailGroupDescriptionField;
    
    private System.DateTime openDateField;
    
    private System.DateTime maturityDateField;
    
    private bool maturityDateFieldSpecified;
    
    private statementProductionEnvelopeStatementAccountSubAccountLoanStatementFormat statementFormatField;
    
    private statementProductionEnvelopeStatementAccountSubAccountLoanBalanceComputationMethod balanceComputationMethodField;
    
    private System.DateTime beginningStatementDateField;
    
    private System.DateTime endingStatementDateField;
    
    private statementProductionEnvelopeStatementAccountSubAccountLoanBeginning beginningField;
    
    private statementProductionEnvelopeStatementAccountSubAccountLoanTransaction[] transactionField;
    
    private statementProductionEnvelopeStatementAccountSubAccountLoanFeeTransaction feeTransactionField;
    
    private statementProductionEnvelopeStatementAccountSubAccountLoanInterestCharge interestChargeField;
    
    private statementProductionEnvelopeStatementAccountSubAccountLoanEnding endingField;
    
    private decimal interestChargedPeriodField;
    
    private bool interestChargedPeriodFieldSpecified;
    
    private decimal interestChargedYTDField;
    
    private decimal interestChargedLastYearField;
    
    private bool interestChargedLastYearFieldSpecified;
    
    private decimal loanFeesChargedPeriodField;
    
    private bool loanFeesChargedPeriodFieldSpecified;
    
    private decimal loanFeesChargedYTDField;
    
    private decimal interestYTDField;
    
    private decimal interestLastYearField;
    
    private bool interestLastYearFieldSpecified;
    
    private System.DateTime endingDueDateField;
    
    private decimal endingDuePaymentField;
    
    private decimal endingDuePaymentPartialAppliedField;
    
    private bool endingDuePaymentPartialAppliedFieldSpecified;
    
    private System.DateTime pastDueDateField;
    
    private bool pastDueDateFieldSpecified;
    
    private decimal pastDuePaymentField;
    
    private bool pastDuePaymentFieldSpecified;
    
    private byte pastDuePaymentCountField;
    
    private bool pastDuePaymentCountFieldSpecified;
    
    private System.DateTime nextScheduledDueDateField;
    
    private decimal nextScheduledDuePaymentField;
    
    private decimal nextScheduledDueInterestField;
    
    private decimal nextScheduledDueLateFeeField;
    
    private bool nextScheduledDueLateFeeFieldSpecified;
    
    private decimal nextScheduledDuePayoffField;
    
    private decimal nextScheduledStandardPaymentField;
    
    private byte daysInBillingCycleField;
    
    private string typeField;
    
    /// <remarks/>
    public uint serial {
        get {
            return this.serialField;
        }
        set {
            this.serialField = value;
        }
    }
    
    /// <remarks/>
    public byte id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountLoanCategory category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public byte typeSerial {
        get {
            return this.typeSerialField;
        }
        set {
            this.typeSerialField = value;
        }
    }
    
    /// <remarks/>
    public string typeDescription {
        get {
            return this.typeDescriptionField;
        }
        set {
            this.typeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public byte branchSerial {
        get {
            return this.branchSerialField;
        }
        set {
            this.branchSerialField = value;
        }
    }
    
    /// <remarks/>
    public string branchDescription {
        get {
            return this.branchDescriptionField;
        }
        set {
            this.branchDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public ushort statementMailGroupSerial {
        get {
            return this.statementMailGroupSerialField;
        }
        set {
            this.statementMailGroupSerialField = value;
        }
    }
    
    /// <remarks/>
    public string statementMailGroupDescription {
        get {
            return this.statementMailGroupDescriptionField;
        }
        set {
            this.statementMailGroupDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime openDate {
        get {
            return this.openDateField;
        }
        set {
            this.openDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime maturityDate {
        get {
            return this.maturityDateField;
        }
        set {
            this.maturityDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maturityDateSpecified {
        get {
            return this.maturityDateFieldSpecified;
        }
        set {
            this.maturityDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountLoanStatementFormat statementFormat {
        get {
            return this.statementFormatField;
        }
        set {
            this.statementFormatField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountLoanBalanceComputationMethod balanceComputationMethod {
        get {
            return this.balanceComputationMethodField;
        }
        set {
            this.balanceComputationMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime beginningStatementDate {
        get {
            return this.beginningStatementDateField;
        }
        set {
            this.beginningStatementDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime endingStatementDate {
        get {
            return this.endingStatementDateField;
        }
        set {
            this.endingStatementDateField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountLoanBeginning beginning {
        get {
            return this.beginningField;
        }
        set {
            this.beginningField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("transaction")]
    public statementProductionEnvelopeStatementAccountSubAccountLoanTransaction[] transaction {
        get {
            return this.transactionField;
        }
        set {
            this.transactionField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountLoanFeeTransaction feeTransaction {
        get {
            return this.feeTransactionField;
        }
        set {
            this.feeTransactionField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountLoanInterestCharge interestCharge {
        get {
            return this.interestChargeField;
        }
        set {
            this.interestChargeField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountLoanEnding ending {
        get {
            return this.endingField;
        }
        set {
            this.endingField = value;
        }
    }
    
    /// <remarks/>
    public decimal interestChargedPeriod {
        get {
            return this.interestChargedPeriodField;
        }
        set {
            this.interestChargedPeriodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool interestChargedPeriodSpecified {
        get {
            return this.interestChargedPeriodFieldSpecified;
        }
        set {
            this.interestChargedPeriodFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal interestChargedYTD {
        get {
            return this.interestChargedYTDField;
        }
        set {
            this.interestChargedYTDField = value;
        }
    }
    
    /// <remarks/>
    public decimal interestChargedLastYear {
        get {
            return this.interestChargedLastYearField;
        }
        set {
            this.interestChargedLastYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool interestChargedLastYearSpecified {
        get {
            return this.interestChargedLastYearFieldSpecified;
        }
        set {
            this.interestChargedLastYearFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal loanFeesChargedPeriod {
        get {
            return this.loanFeesChargedPeriodField;
        }
        set {
            this.loanFeesChargedPeriodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool loanFeesChargedPeriodSpecified {
        get {
            return this.loanFeesChargedPeriodFieldSpecified;
        }
        set {
            this.loanFeesChargedPeriodFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal loanFeesChargedYTD {
        get {
            return this.loanFeesChargedYTDField;
        }
        set {
            this.loanFeesChargedYTDField = value;
        }
    }
    
    /// <remarks/>
    public decimal interestYTD {
        get {
            return this.interestYTDField;
        }
        set {
            this.interestYTDField = value;
        }
    }
    
    /// <remarks/>
    public decimal interestLastYear {
        get {
            return this.interestLastYearField;
        }
        set {
            this.interestLastYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool interestLastYearSpecified {
        get {
            return this.interestLastYearFieldSpecified;
        }
        set {
            this.interestLastYearFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime endingDueDate {
        get {
            return this.endingDueDateField;
        }
        set {
            this.endingDueDateField = value;
        }
    }
    
    /// <remarks/>
    public decimal endingDuePayment {
        get {
            return this.endingDuePaymentField;
        }
        set {
            this.endingDuePaymentField = value;
        }
    }
    
    /// <remarks/>
    public decimal endingDuePaymentPartialApplied {
        get {
            return this.endingDuePaymentPartialAppliedField;
        }
        set {
            this.endingDuePaymentPartialAppliedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endingDuePaymentPartialAppliedSpecified {
        get {
            return this.endingDuePaymentPartialAppliedFieldSpecified;
        }
        set {
            this.endingDuePaymentPartialAppliedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime pastDueDate {
        get {
            return this.pastDueDateField;
        }
        set {
            this.pastDueDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pastDueDateSpecified {
        get {
            return this.pastDueDateFieldSpecified;
        }
        set {
            this.pastDueDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal pastDuePayment {
        get {
            return this.pastDuePaymentField;
        }
        set {
            this.pastDuePaymentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pastDuePaymentSpecified {
        get {
            return this.pastDuePaymentFieldSpecified;
        }
        set {
            this.pastDuePaymentFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public byte pastDuePaymentCount {
        get {
            return this.pastDuePaymentCountField;
        }
        set {
            this.pastDuePaymentCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pastDuePaymentCountSpecified {
        get {
            return this.pastDuePaymentCountFieldSpecified;
        }
        set {
            this.pastDuePaymentCountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime nextScheduledDueDate {
        get {
            return this.nextScheduledDueDateField;
        }
        set {
            this.nextScheduledDueDateField = value;
        }
    }
    
    /// <remarks/>
    public decimal nextScheduledDuePayment {
        get {
            return this.nextScheduledDuePaymentField;
        }
        set {
            this.nextScheduledDuePaymentField = value;
        }
    }
    
    /// <remarks/>
    public decimal nextScheduledDueInterest {
        get {
            return this.nextScheduledDueInterestField;
        }
        set {
            this.nextScheduledDueInterestField = value;
        }
    }
    
    /// <remarks/>
    public decimal nextScheduledDueLateFee {
        get {
            return this.nextScheduledDueLateFeeField;
        }
        set {
            this.nextScheduledDueLateFeeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nextScheduledDueLateFeeSpecified {
        get {
            return this.nextScheduledDueLateFeeFieldSpecified;
        }
        set {
            this.nextScheduledDueLateFeeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal nextScheduledDuePayoff {
        get {
            return this.nextScheduledDuePayoffField;
        }
        set {
            this.nextScheduledDuePayoffField = value;
        }
    }
    
    /// <remarks/>
    public decimal nextScheduledStandardPayment {
        get {
            return this.nextScheduledStandardPaymentField;
        }
        set {
            this.nextScheduledStandardPaymentField = value;
        }
    }
    
    /// <remarks/>
    public byte daysInBillingCycle {
        get {
            return this.daysInBillingCycleField;
        }
        set {
            this.daysInBillingCycleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanCategory {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanStatementFormat {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanBalanceComputationMethod {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanBeginning {
    
    private decimal balanceField;
    
    private decimal annualRateField;
    
    private decimal dailyPeriodicRateField;
    
    private statementProductionEnvelopeStatementAccountSubAccountLoanBeginningVariableRateOption variableRateOptionField;
    
    private string typeField;
    
    /// <remarks/>
    public decimal balance {
        get {
            return this.balanceField;
        }
        set {
            this.balanceField = value;
        }
    }
    
    /// <remarks/>
    public decimal annualRate {
        get {
            return this.annualRateField;
        }
        set {
            this.annualRateField = value;
        }
    }
    
    /// <remarks/>
    public decimal dailyPeriodicRate {
        get {
            return this.dailyPeriodicRateField;
        }
        set {
            this.dailyPeriodicRateField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountLoanBeginningVariableRateOption variableRateOption {
        get {
            return this.variableRateOptionField;
        }
        set {
            this.variableRateOptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanBeginningVariableRateOption {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanTransaction {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("category", typeof(statementProductionEnvelopeStatementAccountSubAccountLoanTransactionCategory))]
    [System.Xml.Serialization.XmlElementAttribute("description", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("grossAmount", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("interest", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("lateFee", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("monetarySerial", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("newBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("postingDate", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("principal", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(statementProductionEnvelopeStatementAccountSubAccountLoanTransactionSource))]
    [System.Xml.Serialization.XmlElementAttribute("transactionSerial", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("transferId", typeof(byte))]
    [System.Xml.Serialization.XmlElementAttribute("transferIdCategory", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("transferOption", typeof(statementProductionEnvelopeStatementAccountSubAccountLoanTransactionTransferOption))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanTransactionCategory {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanTransactionSource {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanTransactionTransferOption {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    category,
    
    /// <remarks/>
    description,
    
    /// <remarks/>
    grossAmount,
    
    /// <remarks/>
    interest,
    
    /// <remarks/>
    lateFee,
    
    /// <remarks/>
    monetarySerial,
    
    /// <remarks/>
    newBalance,
    
    /// <remarks/>
    postingDate,
    
    /// <remarks/>
    principal,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    transactionSerial,
    
    /// <remarks/>
    transferId,
    
    /// <remarks/>
    transferIdCategory,
    
    /// <remarks/>
    transferOption,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanFeeTransaction {
    
    private statementProductionEnvelopeStatementAccountSubAccountLoanFeeTransactionOpenEndLoanFeeIndicator openEndLoanFeeIndicatorField;
    
    private uint transactionSerialField;
    
    private uint monetarySerialField;
    
    private System.DateTime postingDateField;
    
    private statementProductionEnvelopeStatementAccountSubAccountLoanFeeTransactionCategory categoryField;
    
    private statementProductionEnvelopeStatementAccountSubAccountLoanFeeTransactionSource sourceField;
    
    private string descriptionField;
    
    private decimal grossAmountField;
    
    private decimal lateFeeField;
    
    private decimal newBalanceField;
    
    private string typeField;
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountLoanFeeTransactionOpenEndLoanFeeIndicator openEndLoanFeeIndicator {
        get {
            return this.openEndLoanFeeIndicatorField;
        }
        set {
            this.openEndLoanFeeIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public uint transactionSerial {
        get {
            return this.transactionSerialField;
        }
        set {
            this.transactionSerialField = value;
        }
    }
    
    /// <remarks/>
    public uint monetarySerial {
        get {
            return this.monetarySerialField;
        }
        set {
            this.monetarySerialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime postingDate {
        get {
            return this.postingDateField;
        }
        set {
            this.postingDateField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountLoanFeeTransactionCategory category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountLoanFeeTransactionSource source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public decimal grossAmount {
        get {
            return this.grossAmountField;
        }
        set {
            this.grossAmountField = value;
        }
    }
    
    /// <remarks/>
    public decimal lateFee {
        get {
            return this.lateFeeField;
        }
        set {
            this.lateFeeField = value;
        }
    }
    
    /// <remarks/>
    public decimal newBalance {
        get {
            return this.newBalanceField;
        }
        set {
            this.newBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanFeeTransactionOpenEndLoanFeeIndicator {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanFeeTransactionCategory {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanFeeTransactionSource {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanInterestCharge {
    
    private uint transactionSerialField;
    
    private uint monetarySerialField;
    
    private System.DateTime postingDateField;
    
    private decimal interestField;
    
    private string typeField;
    
    /// <remarks/>
    public uint transactionSerial {
        get {
            return this.transactionSerialField;
        }
        set {
            this.transactionSerialField = value;
        }
    }
    
    /// <remarks/>
    public uint monetarySerial {
        get {
            return this.monetarySerialField;
        }
        set {
            this.monetarySerialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime postingDate {
        get {
            return this.postingDateField;
        }
        set {
            this.postingDateField = value;
        }
    }
    
    /// <remarks/>
    public decimal interest {
        get {
            return this.interestField;
        }
        set {
            this.interestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanEnding {
    
    private decimal balanceField;
    
    private decimal annualRateField;
    
    private decimal dailyPeriodicRateField;
    
    private statementProductionEnvelopeStatementAccountSubAccountLoanEndingVariableRateOption variableRateOptionField;
    
    private string typeField;
    
    /// <remarks/>
    public decimal balance {
        get {
            return this.balanceField;
        }
        set {
            this.balanceField = value;
        }
    }
    
    /// <remarks/>
    public decimal annualRate {
        get {
            return this.annualRateField;
        }
        set {
            this.annualRateField = value;
        }
    }
    
    /// <remarks/>
    public decimal dailyPeriodicRate {
        get {
            return this.dailyPeriodicRateField;
        }
        set {
            this.dailyPeriodicRateField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountLoanEndingVariableRateOption variableRateOption {
        get {
            return this.variableRateOptionField;
        }
        set {
            this.variableRateOptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountLoanEndingVariableRateOption {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountShare {
    
    private uint serialField;
    
    private byte idField;
    
    private string descriptionField;
    
    private statementProductionEnvelopeStatementAccountSubAccountShareCategory categoryField;
    
    private statementProductionEnvelopeStatementAccountSubAccountShareRegDLimiting regDLimitingField;
    
    private byte typeSerialField;
    
    private string typeDescriptionField;
    
    private byte branchSerialField;
    
    private string branchDescriptionField;
    
    private ushort statementMailGroupSerialField;
    
    private string statementMailGroupDescriptionField;
    
    private System.DateTime openDateField;
    
    private System.DateTime closeDateField;
    
    private bool closeDateFieldSpecified;
    
    private System.DateTime maturityDateField;
    
    private bool maturityDateFieldSpecified;
    
    private statementProductionEnvelopeStatementAccountSubAccountSharePerson personField;
    
    private System.DateTime beginningStatementDateField;
    
    private System.DateTime endingStatementDateField;
    
    private statementProductionEnvelopeStatementAccountSubAccountShareBeginning beginningField;
    
    private statementProductionEnvelopeStatementAccountSubAccountShareTransaction[] transactionField;
    
    private statementProductionEnvelopeStatementAccountSubAccountShareEnding endingField;
    
    private decimal dividendYTDField;
    
    private bool dividendYTDFieldSpecified;
    
    private decimal certificatePenaltyYTDField;
    
    private bool certificatePenaltyYTDFieldSpecified;
    
    private string typeField;
    
    /// <remarks/>
    public uint serial {
        get {
            return this.serialField;
        }
        set {
            this.serialField = value;
        }
    }
    
    /// <remarks/>
    public byte id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountShareCategory category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountShareRegDLimiting regDLimiting {
        get {
            return this.regDLimitingField;
        }
        set {
            this.regDLimitingField = value;
        }
    }
    
    /// <remarks/>
    public byte typeSerial {
        get {
            return this.typeSerialField;
        }
        set {
            this.typeSerialField = value;
        }
    }
    
    /// <remarks/>
    public string typeDescription {
        get {
            return this.typeDescriptionField;
        }
        set {
            this.typeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public byte branchSerial {
        get {
            return this.branchSerialField;
        }
        set {
            this.branchSerialField = value;
        }
    }
    
    /// <remarks/>
    public string branchDescription {
        get {
            return this.branchDescriptionField;
        }
        set {
            this.branchDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public ushort statementMailGroupSerial {
        get {
            return this.statementMailGroupSerialField;
        }
        set {
            this.statementMailGroupSerialField = value;
        }
    }
    
    /// <remarks/>
    public string statementMailGroupDescription {
        get {
            return this.statementMailGroupDescriptionField;
        }
        set {
            this.statementMailGroupDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime openDate {
        get {
            return this.openDateField;
        }
        set {
            this.openDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime closeDate {
        get {
            return this.closeDateField;
        }
        set {
            this.closeDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool closeDateSpecified {
        get {
            return this.closeDateFieldSpecified;
        }
        set {
            this.closeDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime maturityDate {
        get {
            return this.maturityDateField;
        }
        set {
            this.maturityDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maturityDateSpecified {
        get {
            return this.maturityDateFieldSpecified;
        }
        set {
            this.maturityDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountSharePerson person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime beginningStatementDate {
        get {
            return this.beginningStatementDateField;
        }
        set {
            this.beginningStatementDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime endingStatementDate {
        get {
            return this.endingStatementDateField;
        }
        set {
            this.endingStatementDateField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountShareBeginning beginning {
        get {
            return this.beginningField;
        }
        set {
            this.beginningField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("transaction")]
    public statementProductionEnvelopeStatementAccountSubAccountShareTransaction[] transaction {
        get {
            return this.transactionField;
        }
        set {
            this.transactionField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountShareEnding ending {
        get {
            return this.endingField;
        }
        set {
            this.endingField = value;
        }
    }
    
    /// <remarks/>
    public decimal dividendYTD {
        get {
            return this.dividendYTDField;
        }
        set {
            this.dividendYTDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dividendYTDSpecified {
        get {
            return this.dividendYTDFieldSpecified;
        }
        set {
            this.dividendYTDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal certificatePenaltyYTD {
        get {
            return this.certificatePenaltyYTDField;
        }
        set {
            this.certificatePenaltyYTDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool certificatePenaltyYTDSpecified {
        get {
            return this.certificatePenaltyYTDFieldSpecified;
        }
        set {
            this.certificatePenaltyYTDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountShareCategory {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountShareRegDLimiting {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountSharePerson {
    
    private uint serialField;
    
    private statementProductionEnvelopeStatementAccountSubAccountSharePersonPersonLinkCategory personLinkCategoryField;
    
    private string firstNameField;
    
    private string middleNameField;
    
    private string lastNameField;
    
    private string typeField;
    
    /// <remarks/>
    public uint serial {
        get {
            return this.serialField;
        }
        set {
            this.serialField = value;
        }
    }
    
    /// <remarks/>
    public statementProductionEnvelopeStatementAccountSubAccountSharePersonPersonLinkCategory personLinkCategory {
        get {
            return this.personLinkCategoryField;
        }
        set {
            this.personLinkCategoryField = value;
        }
    }
    
    /// <remarks/>
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public string middleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountSharePersonPersonLinkCategory {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountShareBeginning {
    
    private decimal balanceField;
    
    private string typeField;
    
    /// <remarks/>
    public decimal balance {
        get {
            return this.balanceField;
        }
        set {
            this.balanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountShareTransaction {
    
    private object[] itemsField;
    
    private ItemsChoiceType1[] itemsElementNameField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("accountNumber", typeof(ulong))]
    [System.Xml.Serialization.XmlElementAttribute("achCompanyDescriptiveDate", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("achCompanyEntryDescription", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("achCompanyId", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("achCompanyName", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("achIdentificationNumber", typeof(ushort))]
    [System.Xml.Serialization.XmlElementAttribute("achName", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("achOriginatingDFIId", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("achStandardEntryClassCode", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("achTraceNumber", typeof(ulong))]
    [System.Xml.Serialization.XmlElementAttribute("achTransactionCode", typeof(byte))]
    [System.Xml.Serialization.XmlElementAttribute("adjustmentOption", typeof(statementProductionEnvelopeStatementAccountSubAccountShareTransactionAdjustmentOption))]
    [System.Xml.Serialization.XmlElementAttribute("apyeAverageBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("apyePeriodEndDate", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("apyePeriodStartDate", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("apyeRate", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("availableAmount", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("category", typeof(statementProductionEnvelopeStatementAccountSubAccountShareTransactionCategory))]
    [System.Xml.Serialization.XmlElementAttribute("certificatePenalty", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("description", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("draftNumber", typeof(byte))]
    [System.Xml.Serialization.XmlElementAttribute("draftTracer", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("feeClassification", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("grossAmount", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("maskedCardNumber", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("merchantName", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("merchantType", typeof(ushort))]
    [System.Xml.Serialization.XmlElementAttribute("monetarySerial", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("newBalance", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("postingDate", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("principal", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("routingNumber", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("settlementDate", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("source", typeof(statementProductionEnvelopeStatementAccountSubAccountShareTransactionSource))]
    [System.Xml.Serialization.XmlElementAttribute("subCategory", typeof(statementProductionEnvelopeStatementAccountSubAccountShareTransactionSubCategory))]
    [System.Xml.Serialization.XmlElementAttribute("terminalCity", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("terminalId", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("terminalLocation", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("terminalState", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("transactionAmount", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("transactionDate", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("transactionReference", typeof(ulong))]
    [System.Xml.Serialization.XmlElementAttribute("transactionSerial", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("transferAccountNumber", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("transferId", typeof(byte))]
    [System.Xml.Serialization.XmlElementAttribute("transferIdCategory", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("transferIdDescription", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("transferName", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("transferOption", typeof(statementProductionEnvelopeStatementAccountSubAccountShareTransactionTransferOption))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountShareTransactionAdjustmentOption {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountShareTransactionCategory {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountShareTransactionSource {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountShareTransactionSubCategory {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountShareTransactionTransferOption {
    
    private string optionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0", IncludeInSchema=false)]
public enum ItemsChoiceType1 {
    
    /// <remarks/>
    accountNumber,
    
    /// <remarks/>
    achCompanyDescriptiveDate,
    
    /// <remarks/>
    achCompanyEntryDescription,
    
    /// <remarks/>
    achCompanyId,
    
    /// <remarks/>
    achCompanyName,
    
    /// <remarks/>
    achIdentificationNumber,
    
    /// <remarks/>
    achName,
    
    /// <remarks/>
    achOriginatingDFIId,
    
    /// <remarks/>
    achStandardEntryClassCode,
    
    /// <remarks/>
    achTraceNumber,
    
    /// <remarks/>
    achTransactionCode,
    
    /// <remarks/>
    adjustmentOption,
    
    /// <remarks/>
    apyeAverageBalance,
    
    /// <remarks/>
    apyePeriodEndDate,
    
    /// <remarks/>
    apyePeriodStartDate,
    
    /// <remarks/>
    apyeRate,
    
    /// <remarks/>
    availableAmount,
    
    /// <remarks/>
    category,
    
    /// <remarks/>
    certificatePenalty,
    
    /// <remarks/>
    description,
    
    /// <remarks/>
    draftNumber,
    
    /// <remarks/>
    draftTracer,
    
    /// <remarks/>
    feeClassification,
    
    /// <remarks/>
    grossAmount,
    
    /// <remarks/>
    maskedCardNumber,
    
    /// <remarks/>
    merchantName,
    
    /// <remarks/>
    merchantType,
    
    /// <remarks/>
    monetarySerial,
    
    /// <remarks/>
    newBalance,
    
    /// <remarks/>
    postingDate,
    
    /// <remarks/>
    principal,
    
    /// <remarks/>
    routingNumber,
    
    /// <remarks/>
    settlementDate,
    
    /// <remarks/>
    source,
    
    /// <remarks/>
    subCategory,
    
    /// <remarks/>
    terminalCity,
    
    /// <remarks/>
    terminalId,
    
    /// <remarks/>
    terminalLocation,
    
    /// <remarks/>
    terminalState,
    
    /// <remarks/>
    transactionAmount,
    
    /// <remarks/>
    transactionDate,
    
    /// <remarks/>
    transactionReference,
    
    /// <remarks/>
    transactionSerial,
    
    /// <remarks/>
    transferAccountNumber,
    
    /// <remarks/>
    transferId,
    
    /// <remarks/>
    transferIdCategory,
    
    /// <remarks/>
    transferIdDescription,
    
    /// <remarks/>
    transferName,
    
    /// <remarks/>
    transferOption,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEnvelopeStatementAccountSubAccountShareEnding {
    
    private decimal balanceField;
    
    private string typeField;
    
    /// <remarks/>
    public decimal balance {
        get {
            return this.balanceField;
        }
        set {
            this.balanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.32559")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.corelationinc.com/ns/statementProduction/v1.0")]
public partial class statementProductionEpilogue {
    
    private byte envelopeCountField;
    
    private byte statementCountField;
    
    private byte accountCountField;
    
    private byte shareCountField;
    
    private byte loanCountField;
    
    private string typeField;
    
    /// <remarks/>
    public byte envelopeCount {
        get {
            return this.envelopeCountField;
        }
        set {
            this.envelopeCountField = value;
        }
    }
    
    /// <remarks/>
    public byte statementCount {
        get {
            return this.statementCountField;
        }
        set {
            this.statementCountField = value;
        }
    }
    
    /// <remarks/>
    public byte accountCount {
        get {
            return this.accountCountField;
        }
        set {
            this.accountCountField = value;
        }
    }
    
    /// <remarks/>
    public byte shareCount {
        get {
            return this.shareCountField;
        }
        set {
            this.shareCountField = value;
        }
    }
    
    /// <remarks/>
    public byte loanCount {
        get {
            return this.loanCountField;
        }
        set {
            this.loanCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}
